apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistem-file-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistem-file-upload
  template:
    metadata:
      labels:
        app: sistem-file-upload
    spec:
      containers:
        - image: zdays/sistem-file-upload:2.1
          name: sistem-file-upload
          env:
            - name: PORT
              value: "8080"
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces
                  key: key
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: spaces
                  key: secret
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sistem-file-upload
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: sistem-file-upload
